/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wrap */

#ifndef _Included_Wrap
#define _Included_Wrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wrap
 * Method:    seqpass
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_edu_stevens_dhutchis_accumuloiter_Wrap_seqpass
  (JNIEnv *, jobject, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
